version: '3.8'

services:
  bot:
    build: .
    container_name: navohub-bot
    restart: unless-stopped
    env_file:
      - config/.env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Tashkent
